# Changes here will be overwritten by Copier
_commit: 679102d
_src_path: https://github.com/python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A pure-python project template
project_name: python template
python_version_primary: '3.11'
team: Python Project Template Authors
