# Changes here will be overwritten by Copier
_commit: a446d93
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: python
add_wiki: true
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A pure-python project template
project_name: python template
python_version_primary: '3.11'
team: Python Project Template Authors
